### ISSUE TITLE
Registering Microsoft Graph Connector Agent Fails

### ISSUE THREAD

**Issue by Preeti1910** [microsoft/powerplatform-actions#113]
I am trying to setup Microsoft Graph connectors for network file share

I created a demo tenant.
Login in azure portal with my demo tenant credentials.
Registered an app and grant permission as per this document https://docs.microsoft.com/en-us/microsoftsearch/on-prem-agent

After this I installed GCA from  https://aka.ms/GCAdownload, then login in GCA using my demo tenant credential. Now when I am trying to register GCA with AppId and client secret of the App registered in above step, I am getting error

![image](https://user-images.githubusercontent.com/13446409/128464992-f681a36a-82b5-4c82-bd19-5a43df03de5e.png)

**Comment by davidjenni** [comment]
@Preeti1910 GCA (MS Connector Agent) has no relationship to the PowerPlatform Actions. Please direct this bug report to that product, see the troubleshooting section for that product:
https://docs.microsoft.com/en-us/MicrosoftSearch/graph-connector-agent#troubleshooting 

>> If the errors are not resolvable, reach support on MicrosoftGraphConnectorsFeedback@service.microsoft.com with the logs.
