### ISSUE TITLE
Cannot find required file 'D:\customizations.xml' when running solution import

### ISSUE THREAD

**Issue by jdiekman** [microsoft/powerplatform-actions#119]
Hi There, 

Fairly new to github actions. Have been using the ALM lab yml code (release-solution-to-prod). When executing a release I get the following error when packing the solution. Seems the pack/release solution yml is looking in the wrong location. Running the workflow manually works fine. It's only when the workflow is triggered from a release it fails like this. 

![image](https://user-images.githubusercontent.com/1011572/134069368-3a06e6c8-e550-4eaf-960b-7489d01985fa.png)

Any help would be greatly appreciated. 

Thanks,
James

**Comment by davidjenni** [comment]
@jdiekman can you post the pack-solution step's YAML you used in your GH workflow? From the screenshot it looks like your flow is using an older version of the PowerPlatform GH Actions and it appears that action was missing solution-folder inputs?
Or do you have an actual GH Actions run I could look at?

**Comment by jdiekman** [comment]
Hi @davidjenni sure thing, here you go. It's basically a copy and paste from the Power Apps GH actions repo. 

name: release-solution-to-prod-v2
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: D365Customisations
       #Do Not change these values
      solution_shipping_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/ship/
      solution_outbound_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_source_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
      solution_release_folder:
       description: 'folder where the released binaries are going to be hosted *do not change*'
       required: true
       default: out/release
  release:
    types: [created]
  

env:
#edit your values here
  BUILD_ENVIRONMENT_URL: <removed>
  PRODUCTION_ENVIRONMENT_URL: <removed>
  CLIENT_ID: <removed>
  TENANT_ID: <removed>

jobs:
  convert-to-managed:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ github.event.inputs.solution_source_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_outbound_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_outbound_folder}}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        managed: true
        solution-output-file: ${{ github.event.inputs.solution_shipping_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{ github.event.inputs.solution_shipping_folder}}/${{ github.event.inputs.solution_name }}.zip

  release-to-staging:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{ github.event.inputs.solution_release_folder}}
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{ github.event.inputs.solution_release_folder}}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true

**Comment by davidjenni** [comment]
@jdiekman thanks for the copy of the relevant failing workflow, this helps solve the mystery:

The sample flow you based your flow on is unfortunately using a pinned version of our actions as version 0.4.0:
```
  uses: microsoft/powerplatform-actions/pack-solution@0.4.0
```

We've since switched the implementation the pack-solution action to use the ```pac solution pack``` implementation, which is more forgiving in path handling and path completion.
Best practice for referencing our GH actions is to not pin them to a specific e.g. 0.4.0 version, but use the ```@v0``` or ```@latest``` tags instead. That way, your workflow will pick up new releases; our team is responsible to keep any of our v0/latest release compatible to previous v0 releases.
Your actions references should look like this:
```
  uses: microsoft/powerplatform-actions/pack-solution@v0
```

Note: General GH Actions guidance is to ALWAYS specify a tag with any action; with a missing @<tag>, the latest commit to the main/default branch would be used. I cannot speak for other GH Action publishers, but we do test and validate before we create and tag a new release.

I'll create a PR to go fix the samples under https://github.com/microsoft/powerplatform-actions-lab/tree/main/sample-workflows to actually follow our own advice...
