### ISSUE TITLE
upgrade-solution inputs are incomplete

### ISSUE THREAD

**Issue by melody-universe** [microsoft/powerplatform-actions#121]
The listed inputs for the `upgrade-solution` action do not include inputs for service principal authentication.

Currently, this only throws a warning, but still successfully upgrades the solution using `app-id`, `client-secret`, and `tenant-id`.

A sample of this behavior can be found [here](https://github.com/melody-universe/multi-solution-alm/runs/3709928184?check_suite_focus=true#step:8:1).

Should be fixed by just updating `upgrade-solution/action.yml`.

**Comment by davidjenni** [comment]
addressed in #204
