### ISSUE TITLE
[publish-solution]: Add ability to inject environment variables

### ISSUE THREAD

**Issue by garrytrinder** [microsoft/powerplatform-actions#129]
I'd like to see the ability to inject environment variables into a solution in a workflow that is deployed as a managed solution into a target environment, not sure if this is on the `publish-solution` or `export-solution` action.

**Comment by davidjenni** [comment]
@garrytrinder this support was recently added as part of #131 and will be part of the upcoming October refresh (due out early next week)

**Comment by garrytrinder** [comment]
Great news! Thanks @davidjenni 👍
