### ISSUE TITLE
Export Actions suddenly stopped working 'pac.exe' cannot start or run due to incompatibity with 64-bit versions of Windows.'

### ISSUE THREAD

**Issue by taimoor-hotiana-bzy** [microsoft/powerplatform-actions#174]
Hello,

All our actions for various export and import solutions have suddenly stopped working since 01/02. Event logs on win 2016 server VM shows a very generic error 'The program or feature "\??\D:\actions-runner\_work\_actions\microsoft\powerplatform-actions\v0\dist\pac\tools\pac.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.'

After spending 2 nights trying to figure out the issue and using almost all version of releases, still no joy. Any help will be greatly appreciated.

Note: I have tried using all versions from 0.4.0 to 0.5.1 with the same result

**Comment by taimoor-hotiana-bzy** [comment]
![error](https://user-images.githubusercontent.com/74422979/152625490-605506d8-51fe-4303-9a39-981ae9c6cb15.PNG)

**Comment by taimoor-hotiana-bzy** [comment]
![error1](https://user-images.githubusercontent.com/74422979/152625530-7ba3dae0-c4d0-4073-b22f-850021d9118b.PNG)

**Comment by kkanakas** [comment]
Pac.exe works on Windows 64, it is built on top of .NET 5.0, we are working for figure out what happened, why the child processes are not being spawned.  I will provide the appropriate update, as soon as we learn more.

**Comment by kkanakas** [comment]
Hey Folks,  We have identified the issue on why this is occuring.  We are working towards a resolution on the matter. We will provide an update tomorrow.

**Comment by MattB-msft** [comment]
Closing this thread and will comment in master thread.
