### ISSUE TITLE
Primary Thread for PowerPlatform actions not working for Github workflows using actions 0.5.1 or older

### ISSUE THREAD

**Issue by MattB-msft** [microsoft/powerplatform-actions#176]
Folks, to keep things together with regard to the issues the folks have been having with the PowerPlatform Actions, and compensations we may need to ask of you, we are going to update this thread going forward and link the other issues to it. 

#174 
#173 
#172 

At this time, we have tracked the issue back to a GitHub Runner update that updated the way actions were checked out. 
This change seems to have impacted actions that rely on the large file system support for gitHub as part of managing assets for actions.  

We are working directly with the github Runner's team actively to resolve this issue. 

We are concurrently working to develop a workaround to the root issue and will post here once we have determined the best way to unblock your workflows.

**Comment by MattB-msft** [comment]
Folks we have deployed a new release [0.5.2 ](https://github.com/microsoft/powerplatform-actions/releases/tag/0.5.2) that will allow your builds to work properly until a full fix is created with GitHub. 

Please update your workflows to use 0.5.2 actions to get around this issue. 

This issue will remain open for comment and feedback and updates to you as we resolve it completely.

**Comment by dharmidharmu** [comment]
@MattB-msft I'm facing below error while using version 0.5.2
![Uploading IMG_20220207_080802.jpg…]()

**Comment by kkanakas** [comment]
Hello, your YML files should now work as usual, the LFS update has been rolled back for runners.

**Comment by rajyraman** [comment]
@kkanakas @MattB-msft - It is working again. Thank you.

![image](https://user-images.githubusercontent.com/5035266/152847540-bf9c99c4-717b-4f5e-b9dd-2ad0e78a62ca.png)

**Comment by MattB-msft** [comment]
Also, as a general rule if you use  /who-am-i or /who-am-o@v0  it will use the v0 tag which we keep pointed at the leading edge.  ( 0.5.3. for the moment) 
for more info on this .. see : https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by MattB-msft** [comment]
Folks we are resolving this at this time as GitHub as communicated that the issue is now fixed on their side.  
Sorry for the disruption here. 

Our next 'normal' release will bring back the git large file system configuration for faster action downloads.
