### ISSUE TITLE
Plugin Reg and Steps

### ISSUE THREAD

**Issue by acehaddock** [microsoft/powerplatform-actions#212]
i do not see a way within the actions here to Reg a plugin or its steps (add or remove them)   

if i am incorrect please point me to the right place.

**Comment by paulbreuler** [comment]
Sorry for the delay, you are correct. At this time registering steps plugins and steps can be done with the Plugin Registration Tool (PRT) or using the Dataverse SDK. 

Please note, that once a plugin is registered and it's steps assigned you can add both the assembly and SDK message processing steps to a Dataverse solution. Once in a solution, you will have a consistent reference for deployment purposes. Meaning you only need to register the plugin in your development environment. After that, using the solution with the required components for deployment to downstream environments will handle registering the plugin assembly and associated steps for you. 

- [Download the plugin registration tool](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/download-tools-nuget?view=op-9-1)
- [Register a plugin](https://docs.microsoft.com/en-us/power-apps/developer/data-platform/register-plug-in)
