### ISSUE TITLE
Flow off after import solution with spn

### ISSUE THREAD

**Issue by crivasestrada** [microsoft/powerplatform-actions#214]
Hello,

I am using import-solution action with service principal authentication. The connection references dependencies are creates and configured before the import. 
The flows are off after importing the solution despite the connection references are ok. This behaviour happen even the flows were on before importing a new version. Is it a expected behaviour?. How can we activated the flow automatically?

Thanks for your help

**Comment by paulbreuler** [comment]
@swapnilbhalgat, I believe you were working on something related to this. Do you have any insight into this?

**Comment by paulbreuler** [comment]
A good reference to start from is the [enabling flows containing connections from another user](https://docs.microsoft.com/en-us/power-apps/maker/data-platform/create-connection-reference#enabling-flows-containing-connections-from-another-user) docs article.
