### ISSUE TITLE
Export Solution: Make solution-output-file input optional

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-actions#22]
If the solution file is specified, then the output can be defaulted to the solutionname.zip.

https://github.com/microsoft/powerplatform-actions/blob/ad020db16b5849acd1f498bbd012a582ddcbb5ac/src/actions/export-solution/index.ts#L23

**Comment by davidjenni** [comment]
thanks, we'll take this into consideration as a, for now, lower prio improvement. The team is still working on getting more actions online.
