### ISSUE TITLE
OIDC Auth Support

### ISSUE THREAD

**Issue by quintok** [microsoft/powerplatform-actions#226]
Do you have plans to provide OIDC federated auth support for service principles?

see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Cwindows#use-the-azure-login-action-with-openid-connect for more information

the azure login github action provides such functionality, associated docs: https://github.com/Azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication

**Comment by brntbeer** [comment]
bump :) Would love to see this if we can get here! especially given https://github.blog/changelog/2022-08-23-github-actions-enhancements-to-openid-connect-support-to-enable-secure-cloud-deployments-at-scale/ and the continued investment

**Comment by davidjenni** [comment]
we had offline conversations on this request: for the next semester, we're booking work in the pac CLI to support the missing MSAL .WithClientAssertion() that will enable this. But no concise ETA, closing for now

AB#2920623
