### ISSUE TITLE
Import Solution: Clarify 

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-actions#23]
I can use "import-as-holding" argument to import managed solution as holding, but "Apply Upgrade" does not seem to be happening and there is no action to do this.

**Comment by davidjenni** [comment]
yes, a apply-upgrade task (or similar) is future work, no ETA yet

**Comment by rajyraman** [comment]
CoE Toolkit has already started using this repo, but it seems that they are not using "Upgrade Solution" yet (https://github.com/microsoft/powerplatform-actionstemplate/blob/main/.github/workflows/deploy-PPSolution-to-prod.yml#L34-L41). Can you please tag the release with the new actions, if they are ready?

**Comment by davidjenni** [comment]
@rajyraman action 'upgrade-solution' has been merged in as #34
