### ISSUE TITLE
Spawn Error while cloning powerplatform repo to internal organization

### ISSUE THREAD

**Issue by amenaafreenn** [microsoft/powerplatform-actions#231]
Hi Everyone,

We are trying to use the power-platform action by cloning it internally to our organization. 

While doing so we are facing issues while using the action.

Below is the error log that we are encountering.

Can anyone help us here on this?

Run albertsons/esgh-powerplatform/export-solution@v0
loading action yaml file: D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0\export-solution\action.yml
::group::export-solution:
export-solution:
  ##[debug]command: D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0\dist\pac\tools\pac.exe, first arg of 12: auth
  Error: failed: spawn UNKNOWN
  Error: failed: spawn UNKNOWN
  ##[debug]command: D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0\dist\pac\tools\pac.exe, first arg of 2: auth
  Error: failed: Error: spawn UNKNOWN
  Error: failed: Error: spawn UNKNOWN
  ::endgroup::
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: export-solution action

**Comment by davidjenni** [comment]
@amenaafreenn please check the yaml of your workflow: does its checkout step specify to enable git LFS?

Ensure the checkout step does have `lfs: true`
```
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
```
[sample](https://github.com/microsoft/powerplatform-actions-lab/blob/dfe36232e2055872f38bbbddaed20658d84ee53a/.github/workflows/export-and-branch-solution.yml#L21)

**Comment by davidjenni** [comment]
@amenaafreenn also, it appears you've cloned/forked our microsoft/powerplatform-actions repo into your own GH org, but are most likely missing the /dist folder.
Note we STRONGLY advise against cloning of our Power Platform GH Actions repo into your own GH org, as you'll miss out future updates, unless you regularly update your fork.
If you want or need to stick with a particular release of our GH Actions, we recommend you author your GH workflow to not use the floating `@v0` or `@latest` tags after our tasks' names, but instead to pin to a particular version, e.g.:

```
    - name: create ephemeral test environment
      uses: microsoft/powerplatform-actions/create-environment@v0.7.1   # pin to the May/June refresh
```

check the version tags under Releases: https://github.com/microsoft/powerplatform-actions/releases
On each monthly release we make, we do tag that release first with a unique version tag, e.g. `v0.7.1` as above. That specific tag is never moved; even if we had to do a hot fix, we'd increase it to e.g. `v0.7.2`

The `v0` and `latest` tags, OTOH, we always do move it to the latest released monthly refresh, e.g. right now `v0` points at `v0.8.1`
