### ISSUE TITLE
Error during cloning powerplatform actions internally 

### ISSUE THREAD

**Issue by amenaafreenn** [microsoft/powerplatform-actions#239]
Hi Team,

We are facing the below issue as file not found error

 org/esgh-powerplatform@v0.7.1

    RUNNER_DEBUG: 1
Error: File not found: 'D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0.7.1\../dist/actions/who-am-i/index.js'
##[debug]System.IO.FileNotFoundException: File not found: 'D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0.7.1\../dist/actions/who-am-i/index.js'
##[debug]File name: 'D:\actions-runner-prd\_work\_actions\albertsons\esgh-powerplatform\v0.7.1\../dist/actions/who-am-i/index.js'
##[debug]   at GitHub.Runner.Sdk.ArgUtil.File(String fileName, String name)
##[debug]   at GitHub.Runner.Worker.Handlers.NodeScriptActionHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
##[debug]Finishing: export-solution action

Can you please help us here?

The location that it is showing is different powerplatform\v0.7.1\../dist/actions/who-am-i/index.js'

We looked in the runner and we see that the file is available in the below location

powerplatform\v0.7.1\dist\actions\who-am-i\index.js'

**Comment by davidjenni** [comment]
@amenaafreenn you are running our GH Actions from your own, forked repository.
```
##[debug]File name: 'D:\actions-runner-prd_work_actions\**albertsons\esgh-powerplatform**\v0.7.1../dist/actions/who-am-i/index.js'
```
Your log shows you're running the actions from a forked repo; when referencing our action from this repo (from any other repo), the log looks different:
```
 ##[debug]command: /home/runner/work/_actions/**microsoft/powerplatform-actions**/v0/dist/pac_linux/tools/pac, first arg of 10: auth
```

While this technically possible to do, it is not our best practice and we cannot support our GH Actions that reside in your forked repository. Please reference our GH Actions directly from this repo, as demonstrated in the readme and the lab sample repos:

```
    steps:
    - name: Are we connected
      uses: microsoft/powerplatform-actions/who-am-i@v0
```

CC: @kkanakas

**Comment by aafre01** [comment]
Please see #524
