### ISSUE TITLE
Support for PowerApps GCC

### ISSUE THREAD

**Issue by anweiss** [microsoft/powerplatform-actions#24]
Do these Actions support [PowerApps in GCC](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-us-government)? Are there any known limitations? Thanks!

**Comment by davidjenni** [comment]
assuming the GH workflow runner has both access to the AAD/CDS endpoints in GCC and can pull GH actions from public GH, yes: should work. If you see issues, we'd like to know

**Comment by SteveWinward** [comment]
I just tested the sample export and branch yaml file against a GCC test environment and it works successfully.

https://github.com/microsoft/powerplatform-actions-lab/blob/main/sample-workflows/export-and-branch-solution.yml
