### ISSUE TITLE
export-solution not creating file

### ISSUE THREAD

**Issue by fcctsorrell** [microsoft/powerplatform-actions#251]
My were running without errors but nothing was being created from the export-solution to be picked up by the next step which loaded the .zip to the artifact store.  Didn't have this problem back in August.  Reverted the export-solution to the 0.8.2 version and it is working again.  Not sure what is broken but the latest version isn't working for me.

**Comment by davidjenni** [comment]
the 1.18.x pac CLI (and the 0.8.2 Actions release based on it) introduced a regression on how it always appended an extra "_managed" to the base name of your exported solution.
This is addressed in the 0.9.2 release (based on pac CLI 1.19.4 w/ the fix)

**Comment by davidjenni** [comment]
@fcctsorrell please validate if the latest 0.9.2 release of the actions resolves your issue; closing issue for now. If you still have this repro on your end, please re-activate but also add more details, e.g. error message from the export-solution action, or a following action that tries to read/unpack the exported solution.zip

**Comment by fcctsorrell** [comment]
@davidjenni Just tested it today.  It fixed the problem.  Thanks.
