### ISSUE TITLE
Solution Environment Variables

### ISSUE THREAD

**Issue by robcaretta-thrivent** [microsoft/powerplatform-actions#271]
Could you point me in the direction of a working example of how to update the solution environment variables via the workflow actions?  I see there is a setting file option in the [import-solution](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution#--settings-file) action.   Also not sure how that settings file should be constructed.

**Comment by paulbreuler** [comment]
I believe you are looking for deployment settings. Check out the following article.

"Pre-populate connection references and environment variables for automated deployments" : https://learn.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools

**Comment by robcaretta-thrivent** [comment]
Thank you, I was able to get this all working.
