### ISSUE TITLE
Choose solution action while importing a solution

### ISSUE THREAD

**Issue by Kristoffer88** [microsoft/powerplatform-actions#274]
Hello.

Is it possible to choose the Solution action while importing a solution?

It seems that it is importing with the Update action, and i can't find a way to change it to the default selected upgrade action.

![SolutionAction](https://user-images.githubusercontent.com/17266686/214304764-3bb304c4-20fc-48cb-8c16-13521904b936.png)

**Comment by tehcrashxor** [comment]
Those are performed by separate actions -- `import-solution` performs an Update, `upgrade-solution` performs an Upgrade
