### ISSUE TITLE
Solution Import Error: Solution Files does not exist & --path is invalid

### ISSUE THREAD

**Issue by jraesly** [microsoft/powerplatform-actions#277]
Hello,

I am receiving two similar errors while trying to import. 
The first error when packing the solution then importing is: "Error: Solution file "D:\a\******\******\out\solutions\******.zip" does not exist".
Second error when packing the solution, uploading to GH artifact store, downloading from GH artifact store, then importing is: "Error: failed: Error: Microsoft PowerPlatform CLI,,Version: 1.7.5+g64e6bc4,,,,Error: Argument '--path' is invalid. The file 'D:\a\*****\*****\*****.zip' could not be found.

I have logs available.

Thank you

**Comment by petrochuk** [comment]
These errors are pretty self explanatory. Please check files actually exist before calling an action
