### ISSUE TITLE
Update-solution-version does not allow you to specify the raw solution version (but PAC does)

### ISSUE THREAD

**Issue by BrainSlugs83** [microsoft/powerplatform-actions#284]
i.e. in pac, I can set the version manually, like:
`solution online-version --solution-name MySolution --solution-version x.y.z.w`

But in update-solution-version there is no parameter to support this; meaning that I would have to parse the version numbers manually, myself if I were to use it. -- This adds extra complexity to our builds, and seems like an oversight...

**Comment by tehcrashxor** [comment]
PAC CLI has two similar but different commands:
- `pac solution online-version` sets the version _within Dataverse_, and accepts a Version formatted as `x.y.z.w`
- `pac solution version` increments the version of a solution file on disk, using the version components 

This action corresponds to that second command `pac solution version`, not `pac solution online-version`.
