### ISSUE TITLE
Solution Import Timeout

### ISSUE THREAD

**Issue by rajyraman** [microsoft/powerplatform-actions#30]
I got this error once when I tried to import the solution for the very first time. The solution imported eventhough the workflow failed, and I did not get the error the second time I tried to import. 
![image](https://user-images.githubusercontent.com/5035266/97493331-eca75c00-19b8-11eb-96c1-676004fa317c.png)

**Comment by davidjenni** [comment]
@rajyraman yes, the current import-solution operates with a single synchronous call to CDS. Once the http connection exceeds ~4 min, the connection gets severed on the service side (even though the import gets processed until its complete on the service side).

We have work in progress to add asynchronous support to both import-solution and export-solution that will be able to poll for completion without stumbling over the 4 min idle http connection timeout

**Comment by bobbyschang** [comment]
@davidjenni do you have any updates on the asynchronous support for import-solution & export-solution? Unable to even finish the GitHub Power actions lab <<http://aka.ms/poweractionslab>> because it keeps timing out at different imports

**Comment by davidjenni** [comment]
Bobby, there's a PR coming to this repo that will enable async for import and export

**Comment by davidjenni** [comment]
@rajyraman @bobbyschang see PR #55 that will enable async; plan is to create a new Actions release next week

**Comment by rajyraman** [comment]
@davidjenni - I just finished recording for Scottish Summit, where I will be presenting about Power Platform Actions. Will next week's release include ApplicationId, Client Secret support as well?

**Comment by davidjenni** [comment]
@rajyraman - the existing initial PR for appID/clientSecret authN on create-env and who-am-i actions in #52 might make it for that release; changing the  other actions to also offer app will NOT be part of that release yet, sorry.

**Comment by rajyraman** [comment]
@davidjenni - That is a relief for me, as I don't have to re-record. I will checkout the Async support next week.
