### ISSUE TITLE
Settings File not created when solution is exported

### ISSUE THREAD

**Issue by karlrissland** [microsoft/powerplatform-actions#302]
When you export a solution, need to check if there are environment variables defined, and if so, create the settings-file so you can modify environment specific parameters as you roll from one environment to another.

Import should not only support supplying a settings file, it should allow you to override environment variables inline, much like the Azure Resource Manager actions do.

**Comment by petrochuk** [comment]
There is [pac solution create-settings](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/solution#pac-solution-create-settings) which can be used after export.
