### ISSUE TITLE
Solution Import Version Issue

### ISSUE THREAD

**Issue by JayanRavanan** [microsoft/powerplatform-actions#32]
![image](https://user-images.githubusercontent.com/72857650/98169978-21e60980-1ee5-11eb-81b6-e23dc270f8bd.png)
When I tried to import the solution, I got the above issue. Is there a way to set a newer version while exporting the solution itself. Tried the current solution-version in export-solution, no luck either.  

Is there a work around here..?

**Comment by rajyraman** [comment]
@JayanRavanan - You can use Microsoft.Xrm.Data.PowerShell module to increment the solution version. e.g. https://github.com/rajyraman/GitHub-Actions-SingaporeUG-Demo/blob/main/.github/workflows/commit-solution-components.yml#L27-L35

**Comment by JayanRavanan** [comment]
Thank you @rajyraman . This helps.

**Comment by davidjenni** [comment]
@JayanRavanan @rajyraman there is work in progress to add solution versioning that auto-increments the solution patch version (i.e. the last tuple member in major,minor.patch) within the solution.xml and storing the latest assigned version in 3 different strategies:
- git tags based (pushed back to origin)
- tracker file based (workflow is responsible to persist or commit the tracker file beyond the workflow)
- directly in the solution.xml (workflow is responsible to persist/commit the code change)

A 4th variant allows to specify the patch version as a workflow variable, e.g. if you have other actions that determine a patch version.

See PR #35

**Comment by davidjenni** [comment]
action has been merged
