### ISSUE TITLE
Import/Export Data Log Files

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [microsoft/powerplatform-actions#366]
The CDS Configuration Migration Tool often swallows warnings/errors and just runs through.  It requires manual inspection of the log file to glean what happened.  It would be great if there was a way to allow the download of the log file that is a results of a running the Import-Data action (Export-Data would be nice too, although it's less common to have issues with that process).  Currently I have to run the CDS Configuration Migration Tool manually with the same data file that I ran in a GitHub action and review my local log file to figure out what went wrong on individual executions.  This isn't feasible for upper environments.  
```[tasklist]
### Tasks
```

**Comment by petrochuk** [comment]
PAC CLI already has [--verbose](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/data#--verbose--v-1) for import/export data commands. It looks like it is not exposed on GitHub Action
