### ISSUE TITLE
not able to run check-solution 

### ISSUE THREAD

**Issue by echvsg** [microsoft/powerplatform-actions#391]
Hi All,
I am running the check solution action and it looks it is not working and gave the following error. 
 Error: AADSTS500014: The service principal for resource 'https://service.powerapps.com/' is disabled. This indicate that a subscription within the tenant has lapsed, or that the administrator for this tenant has disabled the application, preventing tokens from being issued for it.
    - name: Check Solution
      uses: microsoft/powerplatform-actions/check-solution@v0
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWER_PLATFORM_CICD_AAD_APP }}
        tenant-id: ${{env.TENANT_ID}}        
        path: ${{env.solution_release_folder}}/${{inputs.solution_name}}_managed.zip     
        checker-logs-artifact-name: ${{inputs.solution_name}}_CheckSolutionLogs
The same app-id combination does seem to work from the pac cli native commands.

 - name: pac check solution
      run: |
       ${{env.PAC_CLI_PATH}}/pac auth create --url ${{env.DEV_ENVIRONMENT_URL}} --name github-actions-cicd-mspp --applicationId ${{env.CLIENT_ID}} --clientSecret ${{ secrets.POWER_PLATFORM_CICD_AAD_APP }} --tenant ${{env.TENANT_ID}}
       ${{env.PAC_CLI_PATH}}/pac solution check --path ${{env.solution_release_folder}}/${{inputs.solution_name}}_managed.zip --outputDirectory c:\samplepackage --geo UnitedStates

Any this is missing or something wrong with the action implementation with service principal.

**Comment by petrochuk** [comment]
It looks to be licensing issue as indicated by AADSTS500014

**Comment by gadamsettie2** [comment]
The issue does not pertain to licensing. When I execute the native pac CLI commands, they work correctly. This situation is an edge case scenario where Power Platform operates in the GovCloud, while the app we have registered for authentication is hosted in public Azure. All other basic actions seem to function as expected.

I also observed an unusual behavior during execution. After authentication, when validating the connection, it appears to pass an additional argument for 'customEndpoint' when invoking the pac solution.

solution check --path E:\actions-runner\_work\*\out\ship\*.zip --ruleSet 0ad12346-e108-40b8-a956-9a8f95ea18c9 --**customEndpoint** https://****.crm9.dynamics.com/ --outputDirectory E:\actions-runner\_work\_temp\PowerAppsChecker\checker-output --saveResults false

   - name: Check Solution
      uses: microsoft/powerplatform-actions/check-solution@v1
      with:
        environment-url: ${{env.DEV_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWER_PLATFORM_CICD_AAD_APP }}
        tenant-id: ${{env.TENANT_ID}}
        path: ${{env.SOLUTION_SHIPPING_FOLDER}}/${{inputs.solution_name}}_${{env.SOLUTION_VERSION}}_managed.zip
        checker-logs-artifact-name: ${{inputs.solution_name}}_CheckSolutionLogs
        cloud: UsGov 

Error:
The Authentication Result: 'c4e6092b-582a-4bf2-8791-ad4a387e5727' authenticated successfully.,Validating connection...,Unable to validate connection to default environment.

**Comment by gadamsettie2** [comment]
@petrochuk: let me know if I have to open a new issue or this can reponed.

**Comment by petrochuk** [comment]
> @petrochuk: let me know if I have to open a new issue or this can reponed.

If this is something specific to you environment then it is better to open Microsoft Support Ticket. Here we can discuss generic build tools, github actions, pac cli issues

**Comment by gadamsettie2** [comment]
Yes, I had a ticket with Microsoft, and since the required functionality was working as expected through the native PAC CLI, it was determined that the issue is related to the GitHub action.
