### ISSUE TITLE
Authentication error during update-solution-version

### ISSUE THREAD

**Issue by dvXcode** [microsoft/powerplatform-actions#417]
While executing a GitHub Workflow that uses microsoft/powerplatform-actions/update-solution-version@v0 to bump the solution version, an error is being thrown related to authentication. 

**The error message is** 
Error: failed: Error: Must provide either username/password or app-id/client-secret/tenant-id for authentication!
![image](https://github.com/microsoft/powerplatform-actions/assets/51912361/8e6e55b2-da05-433f-b85b-0bc2efee92d2)

**To Reproduce:**
The workflow that is triggering this error is the simplest one and is used to work on a solution from Power Platform. The error is thrown at the stage of bumping the solution version. Here are the steps to reproduce:

1)Trigger the GitHub workflow with workflow_dispatch by providing the solution_name.
2)The workflow then executes the following steps:

- It checks out the latest version of the repository.
- Runs the who-am-i action.
- Executes the export-solution action.
- Unpacks the solution with the unpack-solution action.

3)When it gets to the Bump version stage, it throws the aforementioned error.

**Expected behavior:**
The action should update the version of the solution using the provided patch-version without any authentication errors as the necessary authentication parameters (environment-url, app-id, client-secret, and tenant-id) have already been provided in the previous actions.

**Additional context:**
It is clear that the action microsoft/powerplatform-actions/update-solution-version@v0 needs either a username/password or app-id/client-secret/tenant-id for authentication, but it's not clear why these need to be provided again as they are already provided in previous actions in the same workflow.

I am attaching the workflow for further reference: 
```
name: export-and-commit-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: TestSolution
       

permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{secrets.DATAVERSE_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFROMSPN }}
        tenant-id: ${{secrets.TENANT_ID}}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{secrets.DATAVERSE_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFROMSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}.zip
        overwrite: true
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.repository.name}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: Bump ${{ github.event.inputs.solution_name }} version to ${{ github.run_number }}
      uses: microsoft/powerplatform-actions/update-solution-version@v0
      with:
        patch-version: "${{ github.run_number }}"

**Comment by tehcrashxor** [comment]
> Expected behavior:
The action should update the version of the solution using the provided patch-version without any authentication errors as the necessary authentication parameters (environment-url, app-id, client-secret, and tenant-id) have already been provided in the previous actions.

Your expectation in invalid, and operating in that manner would in fact be a security issue.
Every action that requires authentication must be provided with credentials.  Each of these actions 
1. authenticates,
2. performs that actions task, then
3. clears the auth state

If the auth state was not cleared afterward, any other task following in the job could leak the credentials, either by accident (dumping to logs) or by malice (uploading to any web endpoint).

**Comment by Sirz3chs** [comment]
I'm actually facing the same.

I think the expected behavior is not well described. The problem is that the action `update-solution-version` and `set-online-solution-version` can't take credential inputs as the other actions.
So the action is unable to authenticate and failed as describe.
The expected behavior should be to be able to pass credentials to these actions.

**Comment by tehcrashxor** [comment]
Ah, thank you @Sirz3chs for pointing that out.  I saw the comment on the by-design behavior in 
> Expected behavior:
[...] the necessary authentication parameters [..] have already been provided in the previous actions.

and then didn't notice the broader issue that the `update-solution-version` _should not_ need authentication, as it is running the `pac solution version` command which does no external communication, just manipulation of local files.

I'll have PR out shortly to remove the Auth from `update-solution-version`, and add the missing auth parameters in the action definition of the `set-online-solution-version` action which does in fact need them.
