### ISSUE TITLE
Commits by anonymous account when importing Power Platform Solution using GitHub Actions

### ISSUE THREAD

**Issue by sunilsbs** [microsoft/powerplatform-actions#433]
Hi Team, 

We have set up the CI CD for our power platform solutions with Jenkins and GitHub actions. When we are invoking github actions for pulling the solution in GitHub, solution is being committed with an unknown account which is not present in our organization. We confirmed that the solution pull commit is made with that unknown account only when we are pulling solution through Power Platform GitHub actions. The unknown account name is Renaat-CDX. 
Can you please help us identify this account and how and when GitHub Actions are using account when importing solution to repository.

Thanks.

**Comment by petrochuk** [comment]
Export solution action calls either [ExportSolution](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/exportsolution?view=dataverse-latest) or [ExportSolutionAsync](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/reference/exportsolutionasync?view=dataverse-latest). It is not using any customer accounts or data besides solution name being exported

**Comment by sunilsbs** [comment]
Hi Andrew, Thank you for the response. as per guidance from this [link](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy) , We are using following two actions post export solution action. 
1. In UnPack we are extracting the files from solution to store in github repo.
2. Branch solution, creating the branch for extracted files on unpack and making the commit.

Can you please help us with which github account it uses to run  the Branch solution action and commit the branch?

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@latest
      with:
        solution-file: ${{ github.event.client_payload.solution_exported_folder}}/${{ github.event.client_payload.solution-name }}.zip
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution-name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@latest
      with:
        solution-folder: ${{ github.event.client_payload.solution_folder}}/${{ github.event.client_payload.solution-name }}
        solution-target-folder: ${{ github.event.client_payload.solution_target_folder}}/${{ github.event.client_payload.solution-name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
