### ISSUE TITLE
Unkown user Renaat-CDX when new branch is created using powerplatform github actions

### ISSUE THREAD

**Issue by varuna11** [microsoft/powerplatform-actions#434]
Hi Team,

We have set up the CI CD for our power platform solutions with Jenkins and GitHub actions. When we are invoking github actions for pulling the solution in GitHub, solution is being committed into a new branch with an unknown account which is not present in our organization. We confirmed that the solution pull commit is made with that unknown account only when we are pulling solution through Power Platform GitHub actions. The unknown account name is Renaat-CDX.
Can you please help us identify this account and how and when  Power Platform GitHub Actions are using account when importing solution to repository.

We are using following two actions post export solution action.

In UnPack we are extracting the files from solution to store in github repo.
Branch solution, creating the branch for extracted files on unpack and making the commit.

Can you please help us with which github account it uses to run the Branch solution action and commit the branch?

Thanks.

**Comment by tehcrashxor** [comment]
The git `user.name` is set [here in branch-solution/index.ts](https://github.com/microsoft/powerplatform-actions/blob/main/src/actions/branch-solution/index.ts#L53C54-L53C108) based on the `GITHUB_ACTOR` environment variable set by GitHub.

Per [GitHub's docs](https://docs.github.com/en/actions/learn-github-actions/variables), this is "The name of the person or app that initiated the workflow."

**Comment by sunilbsharma** [comment]
Hi Team,
I am also getting to see the same account in my org when importing a solution using Power Platform github actions as per this link https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy 
Kindly suggest and help us understand how is this happening.
![image](https://github.com/microsoft/powerplatform-actions/assets/2525444/9f52c8a4-4603-44b9-b132-682833b4f325)

**Comment by varuna11** [comment]
I am able to print GITHUB_ACTOR in the workflow calling power platform actions and it is not "Renaat-CDX". We have tried to call "Branch Solution Action" from different Github repos and projects and all the commits are from "Renaat-CDX" instead of the correct "Github_Actor".

**Comment by tehcrashxor** [comment]
Via some printf style debugging, the `branch-solution` action is getting the correct value, and succesfully setting it in the git config
![image](https://github.com/microsoft/powerplatform-actions/assets/3751389/c3b7f918-c14a-4351-96a9-efd3bf5239c2)

GitHub displays the commit with that "Renaat-CDX" user as that author:
![image](https://github.com/microsoft/powerplatform-actions/assets/3751389/626ac400-85a5-43f1-abd4-ab6323b6534a)

but pulling down that branch from origin and looking at the git log, the commit does actually have the author set to the expected GITHUB_ACTOR value:
![image](https://github.com/microsoft/powerplatform-actions/assets/3751389/ce4e44a6-f926-4702-93cc-b8629f5fb0cb)

**Comment by varuna11** [comment]
Hi, still getting the same issue, Renaat-CDx is visibile on Github UI. Is the new code that you have merged in reflected in version 1.0.0 on Github Actions? 
<img width="837" alt="power-version" src="https://github.com/microsoft/powerplatform-actions/assets/105763854/7459fb38-f7f6-48f4-98d9-10d220513220">
