### ISSUE TITLE
spawn Unknown error when running synced offline power platform actions in UsGovDoD cloud

### ISSUE THREAD

**Issue by DevonAleshireMSFT** [microsoft/powerplatform-actions#445]
I am getting an error when running synced offline power platform actions on GitHub Enterprise server in US Gov DoD cloud.

I originally tested the power platform actions in an IL4-GCCH environment and was successful. After testing in IL4 I wanted to test in IL5-DoD tenant. 

*IL5 tenant uses GitHub Enterprise server and requires manually syncing actions.

Steps

1. [Manually Synced](https://docs.github.com/en/enterprise-server@3.9/admin/github-actions/managing-access-to-actions-from-githubcom/manually-syncing-actions-from-githubcom) the power-platform-actions using action-sync tool to enterprise server. 
2. Followed [basic tutorial ](https://learn.microsoft.com/en-us/power-platform/alm/tutorials/github-actions-deploy) for automating solution deployment 

I have double checked the yaml file syntax and service principal settings / secret. When executing from IL5 I did have to update the cloud to UsGovDod. Looking to determine if this is an issue on my side our the code behind when communicating with DoD cloud.

**Error**
![image](https://github.com/microsoft/powerplatform-actions/assets/137913782/0d0547f4-ed0d-4b33-bffa-2f31368dd3a4)

**Debug**
![image](https://github.com/microsoft/powerplatform-actions/assets/137913782/00b03b9c-d512-4eff-9ea7-11cc5a475385)

**Workflow**
```yaml
name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      # Change this value
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: ALMDemoSolution
       #Do Not change these values
      solution_exported_folder:
        description: 'folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder: 
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
env:
#edit your values here
  ENVIRONMENT_URL: '<URL>'
  CLIENT_ID: '<Client Id>'
  TENANT_ID: '<Tenant Id>'
permissions:
  contents: write
jobs:
  export-from-dev:
    runs-on: [<Runner Tag>]
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: <synced repo>/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        cloud: UsGovDod


    - name: export-solution action
      uses: <synced repo>/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        cloud: UsGovDod
        
    - name: unpack-solution action
      uses: <synced repo>/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: <synced repo>/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
        solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true```

**Comment by DevonAleshireMSFT** [comment]
Running with latest, it advises PAC needs to be installed on runner. Thinking this might be the issue... ?

![image](https://github.com/microsoft/powerplatform-actions/assets/137913782/291d1341-ffe4-449d-a898-de8b33ac28ca)

**Comment by petrochuk** [comment]
We documented changes for v1 actions: https://learn.microsoft.com/en-us/power-platform/alm/devops-github-available-actions#helper-tasks

**Comment by DevonAleshireMSFT** [comment]
Perfect! Updating the jobs to v1 and adding the install Power Platform tools task has corrected the issue. Thank you @petrochuk
