### ISSUE TITLE
Data-Import action reports success when validation fails

### ISSUE THREAD

**Issue by Joseph-Duty-VA** [microsoft/powerplatform-actions#462]
When I attempt to import a data file and the validation fails, the action reports success even though the data didnt get imported successfully.  Interestingly, when Export-data runs and fails validation, it reports a failure.  It is deceiving that the action is considered successful even though it didn't execute.  

Here is a snippet of our log file.  

import-data:
  authN to env. authType:SPN authScheme:; cloudInstance: Public; envUrl: ***
  '***' authenticated successfully.
  Validating connection...
  Connected to... XXXXXXXXXXXX
  Connected as ***
  Authentication profile created
      * DATAVERSE                                ***/ : ***     UsGov
  
  The Authentication Result: '***' authenticated successfully.,Validating connection...,Connected to... XXXXXXX,Connected as ***,Authentication profile created,    * DATAVERSE                                ***/ : ***     UsGov,
  Calling pac cli inputs: data import --data XXXXXXXXXXXX.zip --verbose false
  Importing data ...
      Parsing import data file
      Parse Complete
      Beginning Import To CRM.. Importing 6 entities - 
      Running Schema Validation
      **Schema Validation failed for Missing fields on Entities, See log for missing fields**
      Import Process completed
  
  Data import is complete
  Action Result: Importing data ...,    Parsing import data file,    Parse Complete,    Beginning Import To CRM.. Importing 6 entities - 3652 records,    Running Schema Validation,    **Schema Validation failed for Missing fields on Entities**, See log for missing fields,    Import Process completed,,Data import is complete
  Authentication profiles and token cache removed
  The Clear Authentication Result: Authentication profiles and token cache removed

**Comment by tehcrashxor** [comment]
Tracking internally as AB#3652270

**Comment by tehcrashxor** [comment]
Fix was released in PAC v1.29.x
powerplatform-actions was updated yesterday with PAC v1.30.6, so issue should be resolved now.
