### ISSUE TITLE
nuget package download from artifactory

### ISSUE THREAD

**Issue by gadamsettie2** [microsoft/powerplatform-actions#472]
Hi,

If I prefer to retrieve the NuGet package from the internal Artifactory rather than using the default nuget.org for the actions-install, what should I do? 

name: 'actions-install'
description: 'Power Platform Actions Install -- Installs the Power Platform CLI (pac) for use in other actions.  Pulls from nuget.org if arguments are not provided.'
inputs:
  nuget-feed-override:
    description: 'Override the nuget feed used to pull the PAC package.  This can be a local folder containing pre-downloaded packages.  Defaults to nuget.org.'
    required: false
    # default: 'https://api.nuget.org/v3/index.json'

Thanks,
Sagar

**Comment by tehcrashxor** [comment]
Supply your own artifactory's feed URL to the `nuget-feed-override` parameter.
If the feed requires authentication, also supply values for `nuget-feed-username` and `nuget-feed-password`

**Comment by gadamsettie2** [comment]
Thank you, @tehcrashxor. That's effective.
