### ISSUE TITLE
Solution Checker action is failing with the error "PACHECKER_PS_FILE_TOO_LARGE"

### ISSUE THREAD

**Issue by wesco-prathapmotupalli** [microsoft/powerplatform-actions#498]
Hi Team,
we are running the solution checker action "uses: microsoft/powerplatform-actions/check-solution@v1" for one of the solution and getting the below error Please suggest on this how can we increase this size to get rid of this?

 Error: ERROR: ErrorId: PACHECKER_PS_FILE_TOO_LARGE; ErrorCategory: InvalidArgument; TargetObject: System.String[]; Exception: System.InvalidOperationException: ERROR: code=PACHECKER_PS_FILE_TOO_LARGE, param=FileUnderAnalysis, message:The file(s) under analysis must be under 30 MB.  D:\a\QOE-SOL\QOE-SOL\out\exported\Solution.zip

**Comment by tehcrashxor** [comment]
30 MB was the largest files that the Checker service would accept previously.
This should now be at 100 MB with the yesterday's release.
