### ISSUE TITLE
GitHub Actions - Connection References not connecting after solution import

### ISSUE THREAD

**Issue by AaronC15** [microsoft/powerplatform-actions#50]
Hello, I'm fairly new to GitHub Actions so I'm not sure if this is an actual problem, or if it's even possible.

We are currently experimenting with GitHub Actions and have a workflow set up which is to export a solution from DEV into TEST, which I copied from these example workflows: https://github.com/microsoft/powerplatform-actions-lab/tree/main/sample-workflows

In this solution we have:

- Canvas App
- Simple flow that sends an email notification to myself
- Connection reference for the "Notification" in that flow

The solution export and import is working fine, but when we run the flow we get this error message:

![image](https://user-images.githubusercontent.com/34095194/106862437-0abedf80-66bf-11eb-9543-ce1721b22f37.png)

Are we missing something in the workflow that will re-connect the connection references after import so that flows successfully run?

I know that when you export/import a solution from PowerApps itself, it will prompt you about connections, but because we're bypassing this stage is this the problem?  We've also attempted this with an Azure DevOps pipeline and got the same result.

Thank you.

**Comment by davidjenni** [comment]
Aaron, the underlying pac CLI the GH import-solution action uses doesn't yet support connection references. But that work is in progress and should appear as preview in here in 3-4 weeks (same work in progress dependency for the AzDevOps task you mentioned).
There
