### ISSUE TITLE
Solution import with Canvas App fails with error 'CanvasApp import: FAILURE: No file with that name found'

### ISSUE THREAD

**Issue by parvezghumra** [microsoft/powerplatform-actions#503]
We're using the Power Platform Github Actions for our ALM processes, which I understand are wrapper around the PAC CLI.

**The 'import-solution' action is failing currently with the following error:**

`The reason given was: CanvasApp import: FAILURE: No file with that name found
  Microsoft PowerPlatform CLI
  Version: 1.28.3+g4ba7dfd`

**The command which fails via Github Actions is:**

`Calling pac cli inputs: solution import --path D:\a\....solution_managed.zip --async true --force-overwrite true --publish-changes false --skip-dependency-check false --convert-to-managed false --max-async-wait-time 60 --activate-plugins true --skip-lower-version false --import-as-holding true --settings-file .....\deploymentsettings.json`

**Our commit process involves invoking the following commands via Github Actions (all of which succeed and do not unpack Canvas Apps)**

`Calling pac cli inputs: solution export --name solution --path D:....\solution.zip --overwrite true --managed false --async true --max-async-wait-time 60`

`Calling pac cli inputs: solution export --name solution --path D:\.....\solution_managed.zip --overwrite true --managed true --async true --max-async-wait-time 60`

`Calling pac cli inputs: solution unpack --zipFile D:\....\solution.zip --folder D:.....\solution --packageType Both --errorlevel Info --singleComponent None --useLcid false --useUnmanagedFileForMissingManaged false --disablePluginRemap false --allowDelete true --allowWrite true --clobber true`

`Calling pac cli inputs: solution unpack --zipFile D:\.....\solution.zip --folder D:\.....\solution --packageType Both --errorlevel Info --singleComponent None --useLcid false --useUnmanagedFileForMissingManaged false --disablePluginRemap false --allowDelete true --allowWrite true --clobber true`

**Our build process involves invoking the following commands via Github Actions (all of which succeed and do not repack Canvas Apps)**

`Calling pac cli inputs: solution pack --zipFile /home/runner/work/....../solution.zip --folder /home/runner/work/...../solution --packageType Both --errorlevel Info --singleComponent None --useLcid false --useUnmanagedFileForMissingManaged false --disablePluginRemap false`

All of this setup was working fine until yesterday

Looking at this response on a [similar issue on the Community forum](https://powerusers.microsoft.com/t5/Building-Power-Apps/Canvas-App-Release-Pipeline-Failing-with-Error-No-file-with-that/m-p/2506698/highlight/true#M623043), it looks like someone resolved this by using version 2 of the corresponding Azure DevOps Power Platform Build Tools. I've verified that I'm using the latest available version of the corresponding Github Action but this hasn't resolved the issue.

Originally posted [here](https://github.com/microsoft/powerplatform-build-tools/issues/684) but reposting in this repository as I'm using Github Actions

**Comment by LeonardSchwenk** [comment]
Same here ! 

Neither local pac cli is work or github action 

I tried to zip the unpacked code locally via pac cli 
`pac solution pack --zipfile solution_unmanged.zip --folder solution` 

>Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163

**Error: Cannot find required file AdditionalUris0_identity.json**

Same meta.xml file as mentioned in the community forum.

```xml
  <AdditionalUris>
    <AdditionalUri>/CanvasApps/solution_AdditionalUris0_identity.json</AdditionalUri>
  </AdditionalUris>
 
  ```

**Comment by snizar007** [comment]
I have been able to reproduce this issue and a bug has been filed for the engineering team.

**Comment by gavenkat78** [comment]
can you try forcing the action to use 1.29.11 version of pac cli and try?

**Comment by parvezghumra** [comment]
Thanks @gavenkat78. I hadn't even realised this was an option. Perhaps I ought to check the action definitions more closely! I'll give this a try now

**Comment by parvezghumra** [comment]
Thanks @gavenkat78. Just to confirm that your suggestion has resolved the issue for us for now. We are using it as a temporary workaround until a new version of the Github Actions are available from Microsoft with the permanent fix.

**Comment by snizar007** [comment]
Thank you @parvezghumra for confirming.
