### ISSUE TITLE
Timeline to GA?

### ISSUE THREAD

**Issue by imjohnbo** [microsoft/powerplatform-actions#51]
Hi there! 👋 I noticed [in the README](https://github.com/microsoft/powerplatform-actions#power-platform-actions) that these actions are listed as pre-release. Do you know of a rough timeline to GA / v1? 🙏

**Comment by davidjenni** [comment]
@imjohnbo -  I'll work with my PM counterparts to determine a timeline to GA/v1; our GA criteria is to have the minimal viable set of GH Actions that we already have in our existing AzDevOps Power Platform Build Tools

CC: @mikkelsen2000

**Comment by davidjenni** [comment]
Today, we've announced General Availability, with support for both Windows and Linux runners

https://github.com/marketplace/actions/powerplatform-actions
