### ISSUE TITLE
Service Principal Support?

### ISSUE THREAD

**Issue by SeaDude** [microsoft/powerplatform-actions#54]
Hello,

Most of the docs say "Service Principal Auth will be supported late 2020". Has it been implemented? If so, how do we set it up? 

Thank you,

**Comment by devkeydet** [comment]
See #14 
https://github.com/microsoft/powerplatform-actions/issues/14

**Comment by rajyraman** [comment]
I already see some work happening around this. See https://github.com/microsoft/powerplatform-actions/pull/52. Hopefully it is soon, along with the updated PAC CLI.

**Comment by SeaDude** [comment]
Sweet. Can't wait to try it out. 

Thank you.
