### ISSUE TITLE
Error 99: Connected to...

### ISSUE THREAD

**Issue by 19JoaoPereira97** [microsoft/powerplatform-actions#67]
I am trying to develop a CI/CD pipeline, however sometimes the error in the attached picture happens from time to time. After some retries the issues seems to disappear and the following runs work fine.

![error](https://user-images.githubusercontent.com/79903620/113278183-80b77f80-92d9-11eb-8d28-71e2edaa6616.PNG)

Exception Id:345b4038-f620-43df-9f32-4e324075d644

Is there any help I can get? 
Thank you in advance.

**Comment by davidjenni** [comment]
@19JoaoPereira97 The way we debug tooling issues in our own workflows is using the pac CLI's trace logs, by adding an upload-artifact action unconditionally at the end of the workflow, see e.g.
https://github.com/microsoft/powerplatform-actions/blob/82736fa736056f9e09e5e389fdd5d6c934e662c5/.github/workflows/rolling-instance-actions.yml#L174

the logs are placed in this folder on the runner:
./dist/pac*/tools/logs/pac-log.txt

My suspicion is, this is an error returned from the Dataverse/CDS side, but clearly, the pac CLI &export-solution action is not surfacing that error properly (which is a bug on our side, sri)

**Comment by nkirstein** [comment]
I was getting the exact same error message and was able to solve the problem by adding the parameter `run-asynchronously: true` to the export-solution action. So I guess it was a timeout issue, at least in my case. The error message wasn't very helpful in figuring this out, unfortunately. 

@davidjenni I tried your suggestion but the resulting log file was empty. This is what I added to the action file:

```
- name: upload pac CLI logs
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: pac-cli-log
        path: ./logs/pac-log.txt
```
The artifact was created but the file was empty. Did I miss anything?

**Comment by davidjenni** [comment]
@nkirstein assuming that any of the powerplatform-actions have run, that log file is NOT expected to be empty, see e.g. this workflow from this repo:
https://github.com/microsoft/powerplatform-actions/actions/runs/1147496290#artifacts

![image](https://user-images.githubusercontent.com/3200210/130281146-8fd5f3e8-76fb-442e-8edd-4a00fb5d6c94.png)
