### ISSUE TITLE
It fails pushing to existing branch.

### ISSUE THREAD

**Issue by arlind-shkrela** [microsoft/powerplatform-actions#69]
I am using microsoft/powerplatform-actions/branch-solution@v0 .When it try to push to existing branch it fails. 
! [rejected]        _preqa_ -> _preqa_ (non-fast-forward)
![PRBranch](https://user-images.githubusercontent.com/26505746/114871082-3239d300-9df9-11eb-985b-c08335b91b36.png)

**Comment by davidjenni** [comment]
@arlind-shkrela this behavior is currently by design to avoid clobbering an existing branch

**Comment by davidjenni** [comment]
current design won't allow clobbering an existing branch
