### ISSUE TITLE
Enable Cloud Parameter to All Actions to Support GCC High Environments

### ISSUE THREAD

**Issue by SteveWinward** [microsoft/powerplatform-actions#73]
There is no way to specify the --cloud parameter that the PAC CLI tool supports with the current action definitions.  The result is that we cannot use GitHub actions with US GCC High and DoD Power Platform environments.  Can we add an optional cloud parameter to each action that defaults to the public endpoint, but enables that to be overridden with other cloud endpoint values?

The current supported cloud types via the PAC tool are below,

Values: Public, Tip1, Tip2, UsGov, UsGovHigh, UsGovDod

**Comment by davidjenni** [comment]
we're working on expanding support to sovereign clouds as well, no ETA yet

**Comment by jraesly** [comment]
Is there an update on this issue? This is critical for us to be able to implement Github Actions on the federal side. Please don't hesitate to shoot me an IM. Would love to connect on this ASAP

**Comment by davidjenni** [comment]
@jraesly this shipped in March as part of this release (also included in @v0 and @latest)
https://github.com/microsoft/powerplatform-actions/releases/tag/v0.6.1
