### ISSUE TITLE
Please remove Build Warnings

### ISSUE THREAD

**Issue by soutchilin** [microsoft/powerplatform-actions#75]
Hi,

I'd like to achieve a clean build (zero-warning strategy). The current actions like "Power Platform Who Am I", "Power Platform Export Solution", "Power Platform Export Solution", "Power Platform Set Solution Version" produce warnings like 
****
##[warning]The names of some imported commands from the module 'Microsoft.Xrm.WebApi.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
****
Can you please ensure, that no general warnings are exposed to the Azure pipeline?

Thanks,
Alexander

**Comment by davidjenni** [comment]
Hi Alexander,
the warning messages you refer to are from the Power Platform Build Tools for Azure DevOps, owned by the same MSFT eng team, but different repo and product. I've logged a bug internally to address this.
I've seen your attempt to contact us on the VS Marketplace; we're addressing the email DL issue.
Thanks!

**Comment by soutchilin** [comment]
Hi David,

Thanks for taking care about it. Unfortunately I didn't get any notificaition from the other repo and cannot find the repo itself. Could you please send me the link with the repo where I can follow up on this issue?

Regards,
Alexander
