### ISSUE TITLE
Trying to import solutions async due to 2 minute solution import timeout, it doesn't seem to work

### ISSUE THREAD

**Issue by brendon-colburn** [microsoft/powerplatform-actions#77]
Hello @davidjenni and team.  I am attempting to use this template as part of the ALM Accelerator for Makers work being done by @devkeydet and the PowerCAT team and I found that I was unable to get it to run in an asynchronous manner for solutions that take longer than 2 minutes to import (which is quite common when you include a simple canvas app in a solution). See below for more details:

### This is the error that is provided
![says-async-is-invalid](https://user-images.githubusercontent.com/16350948/117719069-ee917980-b1aa-11eb-9b22-84183fe40c4e.jpg)

### This is my configuration
![run-async-issettotrue](https://user-images.githubusercontent.com/16350948/117719141-0668fd80-b1ab-11eb-823d-e8a488eb09db.jpg)

Let me know if I'm missing something here.

Thanks!

**Comment by rajyraman** [comment]
@brendon-colburn - Try using @main instead of a specific version for import solution. That property does exist in the action.

**Comment by davidjenni** [comment]
@brendon-colburn please update your work flow to use at least '@v0.2.0' or '@latest'; the 0.1.8 from last fall didn't expose asynchronous imports. The result with using a synchronous connection, the datacenter http proxies in front of the Dataverse/CDS API do terminate any idle http connection after ~2-4 min, resulting in the error you experience since the 0.1.8 did NOT honor or implement the asynch behavior
We are debating to change the default to asynchronous, unless the user asks for synch operations

**Comment by davidjenni** [comment]
>  @brendon-colburn - Try using @main instead of a specific version for import solution. That property does exist in the action.
@rajyraman this isn't the best practice that GH Actions at large recommend, as the main branch is not always guaranteed to be in a fully validated state. Best practice is to either float with the '@v0' or '@latest' tags

**Comment by brendon-colburn** [comment]
@rajyraman , that did work for me thanks for the tip.  @davidjenni , I will incorporate the v0 or latest instead with my next commit to make sure I am using best practices.  You bring up a great point about having async be default.  I think this would honestly be the best approach as a lot of these implementations are using an async approach for the rest of the operations anyway and it's very easy to run into the 2 min timeout.  That's my two cents, thank you both for your help and assistance.

**Comment by rajyraman** [comment]
@davidjenni @brendon-colburn - I was using main or commit id so far, as this was not in the Marketplace and the tags were behind what is in the main branch. Should be OK now since there is a Marketplace listing.
