### ISSUE TITLE
Add maximum wait time for async requests as parameter/attribute to Import Solution action

### ISSUE THREAD

**Issue by korytiak** [microsoft/powerplatform-actions#85]
For larger projects, some solutions will go past 60 minutes which is set as a default in pac. However it is possible to pass other value this way:

-max-async-wait-time: Maximum asynchronous wait time in minutes. Default value is 60 mintues (alias: -wt)

Could you please make use of this existing functionality and expose an attribute to set this value? It would be very much appreciated.

**Comment by davidjenni** [comment]
@korytiak that by itself won't help in all situation, e.g. when using appID/ClientSecret authN, the OAuth access token expires after 60 min and the current MSAL ConfidentialClientAppBuilder doesn't offer to reacquire a new AT using the refresh token.
See also #86
